export declare const zValidator: {
    <T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> | import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>>, Target extends keyof import("hono").ValidationTargets, E extends import("hono").Env, P extends string, In = T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> ? import("zod/v3").input<T> : T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod/v4/core").input<T> : never, Out = T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> ? import("zod/v3").output<T> : T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").infer<T> : never, I extends import("hono").Input = {
        in: (undefined extends In ? true : false) extends true ? { [K in Target]?: ([In] extends [import("hono").ValidationTargets[K]] ? In : import("hono/validator").InferInput<In, K, import("hono/types").ParsedFormValue>) | undefined; } : { [K_1 in Target]: [In] extends [import("hono").ValidationTargets[K_1]] ? In : import("hono/validator").InferInput<In, K_1, import("hono/types").ParsedFormValue>; };
        out: { [K_2 in Target]: Out; };
    }, V extends I = I>(target: Target, schema: T, hook?: undefined, options?: {
        validationFunction: (schema: T, value: import("hono").ValidationTargets[Target]) => (T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").ZodSafeParseResult<any> : import("zod/v3").SafeParseReturnType<any, any>) | Promise<T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").ZodSafeParseResult<any> : import("zod/v3").SafeParseReturnType<any, any>>;
    }): import("hono").MiddlewareHandler<E, P, V, Response & import("hono").TypedResponse<T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").ZodSafeParseError<import("zod").infer<T>> : T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> ? import("zod/v3").SafeParseError<import("zod/v3").input<T>> : never, 400, "json">>;
    <T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> | import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>>, Target extends keyof import("hono").ValidationTargets, E extends import("hono").Env, P extends string, HookFn extends import("@hono/zod-validator").Hook<InferredValue, E, P, Target, {}, T>, In = T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> ? import("zod/v3").input<T> : T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod/v4/core").input<T> : never, Out = T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> ? import("zod/v3").output<T> : T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").infer<T> : never, I extends import("hono").Input = {
        in: (undefined extends In ? true : false) extends true ? { [K in Target]?: ([In] extends [import("hono").ValidationTargets[K]] ? In : import("hono/validator").InferInput<In, K, import("hono/types").ParsedFormValue>) | undefined; } : { [K_1 in Target]: [In] extends [import("hono").ValidationTargets[K_1]] ? In : import("hono/validator").InferInput<In, K_1, import("hono/types").ParsedFormValue>; };
        out: { [K_2 in Target]: Out; };
    }, V extends I = I, InferredValue = T extends import("zod/v3").ZodType<any, import("zod/v3").ZodTypeDef, any> ? import("zod/v3").TypeOf<T> : T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").infer<T> : never>(target: Target, schema: T, hook?: HookFn, options?: {
        validationFunction: (schema: T, value: import("hono").ValidationTargets[Target]) => (T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").ZodSafeParseResult<any> : import("zod/v3").SafeParseReturnType<any, any>) | Promise<T extends import("zod/v4/core").$ZodType<unknown, unknown, import("zod/v4/core").$ZodTypeInternals<unknown, unknown>> ? import("zod").ZodSafeParseResult<any> : import("zod/v3").SafeParseReturnType<any, any>>;
    }): import("hono").MiddlewareHandler<E, P, V, HookFn extends (value: any, c: any) => infer R ? R extends Promise<infer PR> ? PR extends import("hono").TypedResponse<infer T_1, infer S extends import("hono/utils/http-status").StatusCode, infer F extends string> ? Response & import("hono").TypedResponse<T_1, S, F> : PR extends Response ? PR : PR extends undefined ? never : never : R extends import("hono").TypedResponse<infer T_2, infer S_1 extends import("hono/utils/http-status").StatusCode, infer F_1 extends string> ? Response & import("hono").TypedResponse<T_2, S_1, F_1> : R extends Response ? R : R extends undefined ? never : never : never>;
};
